Создан только Respons  так как Нужно получать весь список стран а уже…
Vozzhd/practicum-android-diploma pull request #147
Opened 2024-10-11 04:37 UTC by SafarySun

… после фильтровать

2024-10-11 17:53 UTC, Tuberosus approved these changes

2024-10-11 17:53 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/AreaDto.kt
> +    val areas: List<AreaDto>?
Кажется, что если регионов не будет, то просто придет пустой массив, не null

2024-10-11 19:27 UTC, Vozzhd requested changes

2024-10-11 19:27 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/AreaDto.kt
>  data class AreaDto(
Мне кажется стоит указать что это именно страныDto

2024-10-11 19:27 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/AreaDto.kt
> +    val areas: List<AreaDto>?
В запросе стран нам не нужны их регионы, только имена и id для выбора

2024-10-12 21:04 UTC, Tuberosus requested changes

2024-10-12 21:04 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/filters/data/FilterCountryRepositoryImpl.kt
> +                        Resource.Success(countries) // Заебись
└(・。・)┘

2024-10-13 14:18 UTC, Vozzhd approved these changes

2024-10-13 14:50 UTC, Tuberosus approved these changes

2024-10-13 14:50 UTC, merged