Поиск можно осуществляеть по обеим уровням Индустрии
Vozzhd/practicum-android-diploma pull request #215
Opened 2024-10-17 19:44 UTC by SafarySun

2024-10-17 20:18 UTC, Vozzhd requested changes

2024-10-17 20:18 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/filters/industries/data/impl/FilterIndustriesRepositoryImpl.kt
> +                                )
Нужны наменования в лямбдах - у нас тут разные it. Непонятно что есть что

2024-10-17 20:18 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/filters/industries/data/impl/FilterIndustriesRepositoryImpl.kt
> +    private fun getAllIndustries(ind: List<Industry>): List<Industry> {
Нейминг - ind это не говорящее название для списка индустрий

2024-10-18 14:48 UTC, Vozzhd approved these changes

2024-10-18 15:02 UTC, Tuberosus approved these changes

2024-10-18 15:03 UTC, merged