Diploma 27
Vozzhd/practicum-android-diploma pull request #34
Opened 2024-09-28 21:17 UTC by ShACKAL762

Добавили граф навигации

2024-09-28 21:57 UTC, ShACKAL762 commented
Если хотите могу добавить кнопку перехода на экран фильтр

2024-09-29 08:28 UTC, Tuberosus requested changes
Лишние action в графе

2024-09-29 08:28 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/info/ui/InfoFragment.kt
Предлагаю более подробно название написать - ```TeamInfoFragment``` например

2024-09-29 08:28 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
тут тоже более подробно, например ```SearchVacancyFragment```

2024-09-29 08:28 UTC, Tuberosus commented on app/src/main/res/layout/info_fragment.xml
такой же вопрос как и к классу

2024-09-29 08:28 UTC, Tuberosus commented on app/src/main/res/layout/search_fragment.xml
такой же вопрос как и к классу

2024-09-29 08:28 UTC, Tuberosus commented on app/src/main/res/navigation/navigation_graph.xml
> +        <action
Перехода на фрагмент избранное с фрагмента поиск нет, переходить будем с помощью боттом меню

2024-09-29 10:00 UTC, Vozzhd requested changes

2024-09-29 13:01 UTC, Tuberosus approved these changes

2024-09-29 14:43 UTC, Vozzhd approved these changes

2024-09-29 15:56 UTC, merged