в search добавлен screenState и model
Vozzhd/practicum-android-diploma pull request #65
Opened 2024-10-03 12:39 UTC by Tuberosus

2024-10-03 14:35 UTC, ShACKAL762 requested changes

2024-10-03 14:35 UTC, ShACKAL762 commented on app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchScreenState.kt
> +}
Есть еще одно состояние 
![image](https://github.com/user-attachments/assets/4e70ff25-6940-49f6-bf2e-efb96e9f5a46)

2024-10-03 16:48 UTC, Vozzhd requested changes

2024-10-03 16:48 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/search/presentation/VacancySearchScreenState.kt
> +    data object PaginationLoading : VacancySearchScreenState
Можно просто сделать изображение загрузки одним элементом который появляется во время пагинации и пропадает после.
Вместо перерисовки всего экрана

2024-10-04 13:18 UTC, Vozzhd approved these changes

2024-10-04 17:10 UTC, ShACKAL762 approved these changes

2024-10-04 20:15 UTC, merged