Добавлен класс для отоброжения состоянийя экрана Избранных Вакансий
Vozzhd/practicum-android-diploma pull request #66
Opened 2024-10-03 13:07 UTC by SafarySun

2024-10-03 14:36 UTC, ShACKAL762 approved these changes

2024-10-03 16:53 UTC, Vozzhd requested changes

2024-10-03 16:53 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/favorite/presintation/FavoriteScreenState.kt
> +    data class ContentState(val vacancies: List<Vacancy>) : FavoriteScreenState
У нас при открытии вакансии будет она загружаться или из интернета или из базы, т.к. это две разных логики то будет ContentFromNetwork и ContentFromDatabase

2024-10-03 16:53 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/favorite/presintation/FavoriteScreenState.kt
> +    object Error : FavoriteScreenState
Я не могу понять в каких случаях она Empty а в каких Error - ошибка только одна будет - вакансии нет (удалена)

2024-10-03 18:47 UTC, Tuberosus requested changes

2024-10-03 18:47 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/favorite/presintation/FavoriteScreenState.kt
Тут 3 экрана, предлагаю обсудить, сколько следует сделать стейтов
![image](https://github.com/user-attachments/assets/c7a240b0-46f6-4ede-9ded-21e9576d5aa0)

2024-10-05 06:10 UTC, Tuberosus approved these changes

2024-10-05 15:21 UTC, merged