Два состояния , Content и Error
Vozzhd/practicum-android-diploma pull request #73
Opened 2024-10-03 15:59 UTC by SafarySun

2024-10-03 17:07 UTC, Vozzhd requested changes

2024-10-03 17:07 UTC, Vozzhd commented on app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/VacancyScreenState.kt
> +    data class Content(val vacancy: Vacancy) : VacancyScreenState
У нас будет вакансия или из сети подгружаться или из базы, два state-а для контента

2024-10-03 18:36 UTC, Tuberosus requested changes

2024-10-03 18:36 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/VacancyScreenState.kt
Проверь по макету, там есть еще состояния
![image](https://github.com/user-attachments/assets/d6290025-6c70-42ab-8d9a-11511f80c9f4) ![image](https://github.com/user-attachments/assets/84269345-7a91-4236-ab76-1ed7ab2138ce)![image](https://github.com/user-attachments/assets/ce82da3b-137d-4055-afcb-68079e218173)

2024-10-03 18:36 UTC, Tuberosus commented on app/src/main/java/ru/practicum/android/diploma/vacancy/presentation/VacancyScreenState.kt
> +    data class Content(val vacancy: Vacancy) : VacancyScreenState
Вот тут не согласен. В обоих случаях мы одну и ту же модель показываем одинаково, единственное, что из базы не будет приходить логотип, но это не влияет на экран и отображение данных.

2024-10-05 06:08 UTC, Tuberosus approved these changes

2024-10-05 07:58 UTC, ShACKAL762 approved these changes

2024-10-05 07:59 UTC, Vozzhd approved these changes

2024-10-05 15:20 UTC, merged